CREATE TABLE IF NOT EXISTS `woocommerce_drip_campaign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_name` varchar(250) NOT NULL,
  `page_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `message_content` text NOT NULL,
  `message_content_hourly` text NOT NULL,
  `created_at` datetime NOT NULL,
  `last_sent_at` datetime NOT NULL,
  `drip_type` enum('default','messenger_bot_engagement_checkbox','messenger_bot_engagement_send_to_msg','messenger_bot_engagement_mme','messenger_bot_engagement_messenger_codes','messenger_bot_engagement_2way_chat_plugin','custom') NOT NULL DEFAULT 'default',
  `campaign_type` enum('messenger','email','sms') NOT NULL DEFAULT 'messenger',
  `engagement_table_id` int(11) NOT NULL,
  `between_start` varchar(50) NOT NULL DEFAULT '00:00',
  `between_end` varchar(50) NOT NULL DEFAULT '23:59',
  `timezone` varchar(250) NOT NULL,
  `message_tag` varchar(255) NOT NULL,
  `total_unsubscribed` int(11) NOT NULL,
  `last_unsubscribed_at` datetime NOT NULL,
  `external_sequence_sms_api_id` varchar(50) NOT NULL,
  `external_sequence_email_api_id` varchar(50) NOT NULL,
  `media_type` enum('fb','ig') NOT NULL DEFAULT 'fb',
  `visual_flow_campaign_id` int(11) NOT NULL,
  `visual_flow_sequence_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `page_id` (`page_id`,`user_id`),
  KEY `xengagementtable_type` (`engagement_table_id`,`drip_type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `woocommerce_drip_campaign_webhook_call` (
  `user_id` int(11) NOT NULL,
  `page_table_id` int(11) NOT NULL,
  `wc_user_id` int(11) NOT NULL,
  `cart_url` text NOT NULL,
  `checkout_url` text NOT NULL,
  `wc_session_unique_id` varchar(255) NOT NULL,
  `woocommerce_drip_campaign_id` int(11) NOT NULL,
  `wc_first_name` varchar(255) NOT NULL,
  `wc_last_name` varchar(255) NOT NULL,
  `wc_email` varchar(255) NOT NULL,
  `wc_mobile` varchar(255) NOT NULL,
  `check_box_unique_id` varchar(255) NOT NULL,
  `action_type` varchar(255) NOT NULL,
  `cart_info` longtext NOT NULL,
  `checkout_info` longtext NOT NULL,
  `confirmation_response` longtext NOT NULL,
  `initial_date` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `wc_first_name_bill` varchar(255) NOT NULL,
  `wc_last_name_bill` varchar(255) NOT NULL,
  `wc_email_bill` varchar(255) NOT NULL,
  `wc_mobile_bill` varchar(255) NOT NULL,
  PRIMARY KEY (`user_id`,`page_table_id`,`wc_user_id`,`woocommerce_drip_campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;